# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cgb03EWv2x0g2JcUdlROYs1v-mI8fm43
"""

import pandas as pd
import numpy as np

# 1. Load cleaned dataset
df = pd.read_csv("Cleaned_S1_Ageing_Study_Dataset_Cleaned.csv")

# 2. Create binary outcome: 1 = suppressed (<50), 0 = not suppressed
#    adjust this if your column name or coding is different
df["vl_suppressed_binary"] = (df["vl_suppressed"] == "<50").astype(int)

# quick check
print(df["vl_suppressed"].value_counts(dropna=False))
print(df["vl_suppressed_binary"].value_counts())

import pandas as pd
import numpy as np
import statsmodels.api as sm

# ==============================
# 1. Load data & define outcome
# ==============================

df = pd.read_csv("Cleaned_S1_Ageing_Study_Dataset_Cleaned.csv")

# Define target: 1 = suppressed (<50), 0 = not suppressed
df["vl_suppressed_binary"] = (df["vl_suppressed"] == "<50").astype(int)

print("Outcome counts:\n", df["vl_suppressed_binary"].value_counts())


# ========================================
# 2. Select predictors & convert numerics
# ========================================

predictor_cols = [
    "enrol_age",
    "sex",
    "cd4_baseline",
    "cd4_latest",
    "vl_baseline",
    "years_on_art",
    "weeks_in_care",
    "any_comorbidity",
    "any_chronic_medicine",
    "anyRenal",
    "diabetes_incident",
    "employment"
]

logit_df = df[predictor_cols + ["vl_suppressed_binary"]].copy()

numeric_cols = [
    "enrol_age", "cd4_baseline", "cd4_latest",
    "vl_baseline", "years_on_art", "weeks_in_care",
    "any_comorbidity", "any_chronic_medicine",
    "anyRenal", "diabetes_incident"
]

# force all numeric columns to real numbers
for col in numeric_cols:
    logit_df[col] = pd.to_numeric(logit_df[col], errors="coerce")


# ============================
# 3. One-hot encode categoricals
# ============================

logit_df_encoded = pd.get_dummies(
    logit_df,
    columns=["sex", "employment"],
    drop_first=True
)

y = logit_df_encoded["vl_suppressed_binary"]
X = logit_df_encoded.drop(columns=["vl_suppressed_binary"])

X = X.apply(pd.to_numeric, errors="coerce")
y = pd.to_numeric(y, errors="coerce")

df_model = pd.concat([y, X], axis=1).dropna()
y = df_model.iloc[:, 0]
X = df_model.iloc[:, 1:]

# record feature names BEFORE converting to numpy
feature_names = X.columns

# add constant
X = sm.add_constant(X)
feature_names = X.columns   # update including "const"


# =========================================
# 4. Convert to numpy & fit logistic model
# =========================================

X_np = X.to_numpy(dtype="float64")
y_np = y.to_numpy(dtype="float64")

logit_model = sm.Logit(y_np, X_np)
logit_result = logit_model.fit()

print(logit_result.summary())


# =========================================
# 5. Build Odds Ratio table with feature names
# =========================================

params = logit_result.params
conf = logit_result.conf_int()   # numpy array shape (k,2)
pvals = logit_result.pvalues

or_table = pd.DataFrame({
    "feature": feature_names,
    "coef": params,
    "OR": np.exp(params),
    "2.5%": np.exp(conf[:, 0]),
    "97.5%": np.exp(conf[:, 1]),
    "p_value": pvals
})

print("\n=== Odds Ratios with 95% CI ===\n")
print(or_table)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

# 1. Use the same predictors as logistic regression
rf_df = df[predictor_cols + ["vl_suppressed_binary"]].dropna()

# 2. One-hot encode categoricals
rf_df_encoded = pd.get_dummies(
    rf_df,
    columns=["sex", "employment"],
    drop_first=True
)

X_rf = rf_df_encoded.drop(columns=["vl_suppressed_binary"])
y_rf = rf_df_encoded["vl_suppressed_binary"]

# 3. Train / test split (optional, just for sanity check)
X_train, X_test, Y_train, Y_test = train_test_split(
    X_rf, y_rf, test_size=0.3, random_state=42, stratify=y_rf
)

# 4. Fit Random Forest model
rf = RandomForestClassifier(
    n_estimators=500,
    random_state=42,
    max_depth=None,
    min_samples_split=5,
    min_samples_leaf=3,
    class_weight="balanced"
)
rf.fit(X_train, Y_train)

# 5. Get feature importances
importances = rf.feature_importances_
feat_names = X_rf.columns

imp_df = pd.DataFrame({
    "feature": feat_names,
    "importance": importances
}).sort_values("importance", ascending=False)

print(imp_df.head(15))

# 6. Plot top 10 feature importances (your RF figure)
top_n = 10
top_imp = imp_df.head(top_n).sort_values("importance", ascending=True)

plt.figure(figsize=(8, 5))
plt.barh(top_imp["feature"], top_imp["importance"])
plt.xlabel("Feature Importance Score")
plt.title("Random Forest Feature Importance for Viral Suppression")
plt.tight_layout()
plt.show()